<!--
The Ryuu Technology License

Copyright 2014 Ryuu Technology by 
KatsuoRyuu <anders-github@drake-development.org>.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
Ryuu Technology shall be visible and readable to anyone using the software 
and shall be written in one of the following ways: Ryuu Technology 
or by using the company logo.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->
<article id="main" class="container special">
					<a href="#" class="image featured"><img src="/design/omt/images/pic06.jpg" alt=""></a>
					<header>
						<h2><a href="#">Den årlige sommerfest</a></h2>
						<span class="byline">
							Hej Fighters - Så er det ved og være tid til vores årlige sommerfest:-)
						</span>
					</header>
					<p>

                        Vi starter med udendørs sommertræning kl 10-12.
                        Derefter kan man gå hjem og gøre sig klar til festen kl 18, hvor vi tænder grillen op.
                    </p>
                    <p>

                        Pris pr. kuvert 100.- drikkelse kan købes i baren.
                        PS: det er okay og ta sin bedre halvdel med.
                    </p>
                    <p>
                        Sidste år havde vi et Baywatch tema, men jeg følte mig lidt alene så og sige.... da kun mig og michael festede i livredder shorts, bar overkrop og fløjte til 
                    </p><center><iframe src="//www.youtube.com/embed/KZqvvy0dfw8" allowfullscreen="" width="560" frameborder="0" height="315"></iframe></center>
                    <p></p>
                    <p>
                        Så vi lave en lille afstemning og temaet denne gang.
                        Betaling senest 4 august til enten mig, Nikolaj Honda Cx Weile, Michael Salomonsen eller Thomas Marck Nielsen.
					</p>
					<footer>
						<a href="#" class="button">Continue Reading</a>
					</footer>
				</article>